### ISSUE TITLE
Estudar documento de arquitetura

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020-1-Grupo-4#12]
**Descrição:**
Realizar estudo sobre Arquitetura de Software.

**Tarefas:**

- [x] Estudar os modelos de arquiteturas.

- [x] Entender a documentação de arquitetura.

**Critérios de Aceitação:**

- [x] Compartilhar as melhores referencias para estudo.
* _Deverá ser compartilhada por essa issue._

**Comment by enzoggqs** [comment]
Realmente todas as referências colocadas pelo @DanielPortods são de ótima qualidade, e acrescento apenas mais uma:
https://www.youtube.com/watch?v=UpYKYaQU0SA

Um vídeo curto, simples e objetivo que mostra os tipos de arquitetura de software.

**Comment by enzoggqs** [comment]
Após isso, se o @DanielPortods  concordar que nossas referências são suficientes, podemos fechar a issue.
